### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by kingRodian** [OriginLive/SpideR#1]
TODO:
 1. - [x] Make program work with depth > 1. Fix parsing of urls
 2. - [ ] Dump data regularly to file to avoid too large a tree
 3. - [ ] Incorrect Settings.json should not crash the program, issue an error message.
 4. - [x] Add a quit command
 5. - [ ] Lacking a Settings.json, the user should be given the option to generate a default one.
 6. - [ ] Add ability to read robots.txt and avoid sites that should not be accessed (patterns like "*?id=*")
 7. - [ ] Make robot more polite (make sure not to flood a site, and make it a default but **optional** setting)
 8. - [x] Add ability to deal with ssl or handshakes. (Curl does this)
 9. - [ ] More customizability, make settings a polymorphic class that has functions to alter logic? (<< this part will be implemented with a scripting language)
10. - [ ] Better linux console.
11. - [ ] Sort the libraries, they should be downloadable, rather than embedded already.
12. - [ ] Make program more into a state machine, polymorphic

**Comment by OriginLive** [comment]
- [ ] Tron's suggestion, make console polymorphic, use string view for text (fix the concatenation)

**Comment by OriginLive** [comment]
- [x] Implement python as the scripting backend, and have it able to sort and manipulate data
(Two examples i can think of are: Have all of the text be in a set; Search for the tags named "object" and "price" under the same dom and output it as a sortable column)
- [ ] Make a solution work as a dynamic/static library
- [ ] Write documentation/wiki and usage for the said library
- [ ] Multithreading
- [ ] Object / lambda commands as opposed to void*
- [ ] Polish
